baseURL = "https://decisiones.github.io/"
# Sets defaultContentLanguageInSubdir = true to make
# Huge render the correct HTML for all languages
# — including English — and store it accordingly
# under their own subdirectories (/en/, /es/, /pt-br/)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Decisiones 2025 Symposium Website"
mainSections = ["post"]

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

disableKinds = ["taxonomy", "RSS"]

[taxonomies]
tag = "tags"

[permalinks]
post = "/:slugorcontentbasename/"
tags = "/tags/:slug"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3

[markup.highlight]
  lineNos = true
  lineNumbersInTable = false
  noClasses = true
  style = "catppuccin-mocha"

[params]
title = "Decisiones 2025 Symposium Website"
description = "Symposium Website"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
hideRSSLink = true           # Hide RSS link

[params.author]
name = "Luiz Carlos Estraviz Rodriguez"
email = "decisiones2025@luizestraviz.com"

[services.rss]
  limit = 42

[pagination]
  pagerSize = 16

[outputs]
  # Generate RSS for home only.
  section = ["html"]
  taxonomy = ["html"]
  term = ["html"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
  [languages.es]
    languageName = "Español"
    weight = 20
  [languages."pt-br"]
    languageName = "Português"
    weight = 30

[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Program"
    pageRef = "/"
    weight = 5
  [[languages.en.menu.main]]
    name = "Venue"
    url = "/en/venue/"
    weight = 10
  [[languages.en.menu.main]]
    name = "Abstracts"
    url = "/en/abstracts/"
    weight = 20
  [[languages.en.menu.main]]
    name = "Field Trip"
    url = "/en/fieldtrip/"
    weight = 30

[languages.es.menu]
  [[languages.es.menu.main]]
    name = "Programa"
    pageRef = "/"
    weight = 5
  [[languages.es.menu.main]]
    name = "Lugar"
    url = "/es/venue/"
    weight = 10
  [[languages.es.menu.main]]
    name = "Resúmenes"
    url = "/es/abstracts/"
    weight = 20
  [[languages.es.menu.main]]
    name = "Día de Campo"
    url = "/es/fieldtrip/"
    weight = 30

[languages."pt-br".menu]
  [[languages."pt-br".menu.main]]
    name = "Programa"
    pageRef = "/"
    weight = 5
  [[languages."pt-br".menu.main]]
    name = "Local"
    url = "/pt-br/venue/"
    weight = 10
  [[languages."pt-br".menu.main]]
    name = "Resumos"
    url = "/pt-br/abstracts/"
    weight = 20
  [[languages."pt-br".menu.main]]
    name = "Dia de Campo"
    url = "/pt-br/fieldtrip/"
    weight = 30
    
[security]
  [security.csp]
    [security.csp.unsafeInline]
      styles = true
      scripts = true
    [security.csp.imgSrc]
      urls = ["'self'", "data:", "https://*.tile.openstreetmap.org"]
    [security.csp.scriptSrc] 
      urls = ["'self'", "https://unpkg.com"]
    [security.csp.styleSrc]
      urls = ["'self'", "https://unpkg.com"]
